set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER $ENV{BUILDROOT_HOST}/bin/aarch64-linux-gcc)
set(PKG_CONFIG_EXECUTABLE $ENV{BUILDROOT_HOST}/bin/pkg-config)
set(CMAKE_FIND_ROOT_PATH
    $ENV{BUILDROOT_HOST}/aarch64-buildroot-linux-gnu/sysroot
)
set(CMAKE_SYSROOT $ENV{BUILDROOT_HOST}/aarch64-buildroot-linux-gnu/sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
